# Generated by Django 5.2.5 on 2025-09-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='category',
            field=models.CharField(choices=[('veg', 'Veg'), ('nonveg', 'Non-Veg')], default='veg', max_length=10),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.TextField(),
        ),
    ]
